export const FETCH_CAMPAIGNS_LIST = 'FETCH_CAMPAIGNS_LIST';
export const FETCH_CAMPAIGNS_LIST_SUCCESS = 'FETCH_CAMPAIGNS_LIST/SUCCESS';
export const FETCH_CAMPAIGNS_LIST_ERROR = 'FETCH_CAMPAIGNS_LIST/ERROR';

export const FETCH_ARCHIVED_CAMPAIGNS_LIST = 'FETCH_ARCHIVED_CAMPAIGNS_LIST';
export const FETCH_ARCHIVED_CAMPAIGNS_LIST_SUCCESS =
  'FETCH_ARCHIVED_CAMPAIGNS_LIST/SUCCESS';
export const FETCH_ARCHIVED_CAMPAIGNS_LIST_ERROR =
  'FETCH_ARCHIVED_CAMPAIGNS_LIST/ERROR';

export const CREATE_NEW_CAMPAIGN = 'CREATE_NEW_CAMPAIGN';
export const CREATE_NEW_CAMPAIGN_SUCCESS = 'CREATE_NEW_CAMPAIGN/SUCCESS';
export const CREATE_NEW_CAMPAIGN_ERROR = 'CREATE_NEW_CAMPAIGN/ERROR';

export const DELETE_CAMPAIGN_BY_ID = 'DELETE_CAMPAIGN_BY_ID';
export const DELETE_CAMPAIGN_BY_ID_SUCCESS = 'DELETE_CAMPAIGN_BY_ID/SUCCESS';
export const DELETE_CAMPAIGN_BY_ID_ERROR = 'DELETE_CAMPAIGN_BY_ID/ERROR';

export const ARCHIVE_CAMPAIGN_BY_ID = 'ARCHIVE_CAMPAIGN_BY_ID';
export const ARCHIVE_CAMPAIGN_BY_ID_SUCCESS = 'ARCHIVE_CAMPAIGN_BY_ID/SUCCESS';
export const ARCHIVE_CAMPAIGN_BY_ID_ERROR = 'ARCHIVE_CAMPAIGN_BY_ID/ERROR';
